In [35]:
import pandas as pd 
df = pd.read_csv("Housing.csv")
df

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

### **Change yes/no columns to 1/0**

In [36]:
df['mainroad'] = df['mainroad'].replace({'yes': 1, 'no': 0})
df['guestroom'] = df['guestroom'].replace({'yes': 1, 'no': 0})
df['basement'] = df['basement'].replace({'yes': 1, 'no': 0})
df['hotwaterheating'] = df['hotwaterheating'].replace({'yes': 1, 'no': 0})
df['airconditioning'] = df['airconditioning'].replace({'yes': 1, 'no': 0})
df['prefarea'] = df['prefarea'].replace({'yes': 1, 'no': 0})
df




price  area  bedrooms  bathrooms  stories  mainroad  guestroom  \
0    13300000  7420         4          2        3         1          0   
1    12250000  8960         4          4        4         1          0   
2    12250000  9960         3          2        2         1          0   
3    12215000  7500         4          2        2         1          0   
4    11410000  7420         4          1        2         1          1   
..        ...   ...       ...        ...      ...       ...        ...   
540   1820000  3000         2          1        1         1          0   
541   1767150  2400         3          1        1         0          0   
542   1750000  3620         2          1        1         1          0   
543   1750000  2910         3          1        1         0          0   
544   1750000  3850         3          1        2         1          0   

     basement  hotwaterheating  airconditioning  parking  prefarea  \
0           0                0                1        2         1   
1           0                0                1        3         0   
2           1                0                0        2         1   
3           1                0                1        3         1   
4           1                0                1        2         0   
..        ...              ...              ...      ...       ...   
540         1                0                0        2         0   
541         0                0                0        0         0   
542         0                0                0        0         0   
543         0                0                0        0         0   
544         0                0                0        0         0   

    furnishingstatus  
0          furnished  
1          furnished  
2     semi-furnished  
3          furnished  
4          furnished  
..               ...  
540      unfurnished  
541   semi-furnished  
542      unfurnished  
543        furnished  
544      unfurnished  

[545 rows x 13 columns]

### **Change furnishing status to number**

In [37]:
df['furnishingstatus'].unique()

array(['furnished', 'semi-furnished', 'unfurnished'], dtype=object)

In [38]:
df['furnishingstatus'] = df['furnishingstatus'].replace({'furnished': 1, 'semi-furnished': 2, "unfurnished":3})


### **Re-scaling lại value ở cột area**


In [39]:
df['area']= df["area"]/1000
df

price  area  bedrooms  bathrooms  stories  mainroad  guestroom  \
0    13300000  7.42         4          2        3         1          0   
1    12250000  8.96         4          4        4         1          0   
2    12250000  9.96         3          2        2         1          0   
3    12215000  7.50         4          2        2         1          0   
4    11410000  7.42         4          1        2         1          1   
..        ...   ...       ...        ...      ...       ...        ...   
540   1820000  3.00         2          1        1         1          0   
541   1767150  2.40         3          1        1         0          0   
542   1750000  3.62         2          1        1         1          0   
543   1750000  2.91         3          1        1         0          0   
544   1750000  3.85         3          1        2         1          0   

     basement  hotwaterheating  airconditioning  parking  prefarea  \
0           0                0                1        2         1   
1           0                0                1        3         0   
2           1                0                0        2         1   
3           1                0                1        3         1   
4           1                0                1        2         0   
..        ...              ...              ...      ...       ...   
540         1                0                0        2         0   
541         0                0                0        0         0   
542         0                0                0        0         0   
543         0                0                0        0         0   
544         0                0                0        0         0   

     furnishingstatus  
0                   1  
1                   1  
2                   2  
3                   1  
4                   1  
..                ...  
540                 3  
541                 2  
542                 3  
543                 1  
544                 3  

[545 rows x 13 columns]

In [50]:
df['price']= df["price"]/10000000

In [51]:
data = df.to_numpy()
data

array([[1.33 , 7.42 , 4.   , ..., 2.   , 1.   , 1.   ],
       [1.225, 8.96 , 4.   , ..., 3.   , 0.   , 1.   ],
       [1.225, 9.96 , 3.   , ..., 2.   , 1.   , 2.   ],
       ...,
       [0.175, 3.62 , 2.   , ..., 0.   , 0.   , 3.   ],
       [0.175, 2.91 , 3.   , ..., 0.   , 0.   , 1.   ],
       [0.175, 3.85 , 3.   , ..., 0.   , 0.   , 3.   ]])

In [52]:
Y = data[:,0]
X = data[:,1:]

In [56]:
X[0]

array([7.42, 4.  , 2.  , 3.  , 1.  , 0.  , 0.  , 0.  , 1.  , 2.  , 1.  ,
       1.  ])

In [53]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=42)
X_train.shape

(365, 12)

In [81]:
import numpy as np
import random
class VectorizedLinearRegression_GradientDescent:
    def __init__(self,lr=0.01,n_epoch=1000):
        self.lr=lr
        self.n_epoch=n_epoch
        self.W = np.random.rand(X.shape[1],1) - 0.5
        self.d = random.random() - 0.5
    def loss(self,X,Y):
        N = len(X) # number of samples
        y_hat = np.dot(X,self.W) + self.d
        f = y_hat - Y
        loss = np.sum(f**2)/N
        return loss
    def predict(self,X):
        y_hat = np.dot(X,self.W) + self.d
        return y_hat
    def fit(self, X,Y):
        N = len(X) # number of samples
        for i in range(self.n_epoch):
            y_hat = np.dot(X,self.W) + self.d
            f = y_hat - Y
            loss = np.sum(f**2)/N
            # Updating m and b
            self.W -= self.lr * (2 * X.T.dot(f) / N)
            self.d -= self.lr * (2 * f.sum()/N)
            print("Epoch",i+1,",loss",loss)
    

In [90]:
model = VectorizedLinearRegression_GradientDescent(lr=0.001,n_epoch=20000)
model.fit(X_train, np.array(y_train).reshape(-1,1))


Epoch 1 ,loss 0.7604451148753273
Epoch 2 ,loss 0.6566338582691438
Epoch 3 ,loss 0.5720479054038918
Epoch 4 ,loss 0.503101043672072
Epoch 5 ,loss 0.44687619017517366
Epoch 6 ,loss 0.4010005415324007
Epoch 7 ,loss 0.363544018989585
Epoch 8 ,loss 0.3329366622508761
Epoch 9 ,loss 0.3079014364663814
Epoch 10 ,loss 0.2873995764962885
Epoch 11 ,loss 0.27058612917091285
Epoch 12 ,loss 0.2567737907431708
Epoch 13 ,loss 0.24540349176651574
Epoch 14 ,loss 0.2360204704230574
Epoch 15 ,loss 0.2282548102337745
Epoch 16 ,loss 0.22180560915952482
Epoch 17 ,loss 0.21642810252608802
Epoch 18 ,loss 0.2119231886309659
Epoch 19 ,loss 0.20812890872510953
Epoch 20 ,loss 0.20491351671053198
Epoch 21 ,loss 0.20216984193504411
Epoch 22 ,loss 0.19981070381026905
Epoch 23 ,loss 0.19776518199741386
Epoch 24 ,loss 0.19597558252381916
Epoch 25 ,loss 0.19439496997933173
Epoch 26 ,loss 0.1929851601699222
Epoch 27 ,loss 0.19171508731366382
Epoch 28 ,loss 0.19055947589470718
Epoch 29 ,loss 0.18949776033032953
Epoch 30 ,

### **Tính loss trên tập data test**

In [91]:
model.loss(X_test, np.array(y_test).reshape(-1,1))

0.015437144967374167

### **Predict thử một mẫu trong data test**

In [92]:
sample = X_test[0]
print("Sample test: ",sample)
model.predict(sample)

Sample test:  [5.9 4.  2.  2.  0.  0.  1.  0.  0.  1.  0.  3. ]


array([0.52589036])